import React from 'react';
import { Info } from 'lucide-react';

export default function LimitationsPanel() {
    return (
        <div className="flex-1 flex flex-col items-center justify-center text-center p-6 bg-slate-50 border border-slate-200">
            <Info size={24} className="text-indigo-500 mb-3" />
            <h3 className="text-xs font-bold text-slate-800 uppercase tracking-widest mb-2">Educational Visualization</h3>
            <p className="text-[10px] text-slate-500 leading-relaxed max-w-xs">
                The following visualization is generated by the Learning Engine to explain how the program typically executes. Execution results shown below are produced by the selected runtime.
            </p>
        </div>
    );
}
